#!/usr/bin/env python3

import os, sys

def create_file():
    path = os.getcwd() + "/decoder"
    fp = open(path + "/register.h", 'w')
    files = sorted(os.listdir(path))

    print("%s" % sys.version)
    fp.write('/* Autogenerated - do not edit */\n\n')
    fp.write("#ifndef DECODER_REGISTER\n")
    fp.write("#define DECODER_REGISTER\n\n")
    fp.write("#include \"decoder.h\"\n\n")
    fp.write("typedef void (*register_function)(void);\n")
    fp.write('static register_function decoder_functions[] = {\n')
    for fn in files:
        basename = os.path.basename(fn)
        if basename.startswith('packet_') and basename.endswith('.c'):
            names = basename[:-2].split('_')
            fp.write("    register_%s,\n" % names[1])
    fp.write('};\n')
    fp.write("#endif\n")
    fp.close()

create_file()
